### ISSUE TITLE
Bibliography migration failing

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/course-digest#58]
When trying to migrate 2 courses (Wellstart v1.2, C@CM v3.4) I get a failure related to bibliography support on each
```
C:\Users\gregb\Documents\OLI\SVN\course-digest\src\resources\workbook.ts:79
      bibrefs.push(bibEntries.get(entry).id);
                                        ^
TypeError: Cannot read properties of undefined (reading 'id')
    at Element.<anonymous> (C:\Users\gregb\Documents\OLI\SVN\course-digest\src\resources\workbook.ts:79:41)
    at LoadedCheerio.each (C:\Users\gregb\Documents\OLI\SVN\course-digest\node_modules\cheerio\lib\api\traversing.js:480:26)
    at WorkbookPage.translate (C:\Users\gregb\Documents\OLI\SVN\course-digest\src\resources\workbook.ts:77:15)
    at C:\Users\gregb\Documents\OLI\SVN\course-digest\src\convert.ts:57:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

These are the courses tested thus far
https://svn.oli.cmu.edu/svn/content/editor/projects/echo-oli-cmu-edu/wellstart-v8fhrc86/branches/v_1_2-echo
https://svn.oli.cmu.edu/svn/content/c_at_cm/c_at_cm/branches/v_3_4-echo

**Comment by rgachuhi** [comment]
This is now fixed and landed in master
